"""Initial schema — 9 tables from plan section 4.

Revision ID: 0001_initial
Revises:
Create Date: 2026-04-13

Hand-written (not autogenerated) because at T02 time there is no live
Postgres to diff against. Tables are created in FK-safe order:

    region_master
    category_mapping_rule
    dataset_version
    place_raw_kakao
    place_normalized
    real_activity_agg
    region_feature
    persona_region_weight
    spot_seed_dataset

``downgrade()`` drops them in the exact reverse order.
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ------------------------------------------------------------------
    # 1. region_master
    # ------------------------------------------------------------------
    op.create_table(
        "region_master",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("region_code", sa.String(length=20), nullable=False),
        sa.Column("sido", sa.String(length=20), nullable=False),
        sa.Column("sigungu", sa.String(length=20), nullable=False),
        sa.Column("emd", sa.String(length=30), nullable=False),
        sa.Column("center_lng", sa.Float(), nullable=False),
        sa.Column("center_lat", sa.Float(), nullable=False),
        sa.Column("bbox_min_lng", sa.Float(), nullable=True),
        sa.Column("bbox_min_lat", sa.Float(), nullable=True),
        sa.Column("bbox_max_lng", sa.Float(), nullable=True),
        sa.Column("bbox_max_lat", sa.Float(), nullable=True),
        sa.Column("area_km2", sa.Float(), nullable=True),
        sa.Column(
            "grid_level",
            sa.SmallInteger(),
            server_default=sa.text("0"),
            nullable=True,
        ),
        sa.Column("target_city", sa.String(length=20), nullable=True),
        sa.Column(
            "is_active",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=True,
        ),
        sa.Column("last_collected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("region_code"),
    )
    op.create_index(
        "idx_region_target_city", "region_master", ["target_city"], unique=False
    )
    op.create_index(
        "idx_region_active", "region_master", ["is_active"], unique=False
    )
    op.create_index(
        "idx_region_last_collected",
        "region_master",
        ["last_collected_at"],
        unique=False,
    )

    # ------------------------------------------------------------------
    # 2. category_mapping_rule
    # ------------------------------------------------------------------
    op.create_table(
        "category_mapping_rule",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "kakao_category_group_code", sa.String(length=10), nullable=True
        ),
        sa.Column("kakao_category_pattern", sa.String(length=200), nullable=True),
        sa.Column("keyword_pattern", sa.String(length=200), nullable=True),
        sa.Column("internal_tag", sa.String(length=30), nullable=False),
        sa.Column(
            "confidence",
            sa.Float(),
            server_default=sa.text("1.0"),
            nullable=True,
        ),
        sa.Column(
            "priority", sa.Integer(), server_default=sa.text("0"), nullable=True
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=True,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )

    # ------------------------------------------------------------------
    # 3. dataset_version
    # ------------------------------------------------------------------
    op.create_table(
        "dataset_version",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("version_name", sa.String(length=50), nullable=False),
        sa.Column("build_type", sa.String(length=20), nullable=False),
        sa.Column("target_city", sa.String(length=20), nullable=True),
        sa.Column("built_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source_window_start", sa.Date(), nullable=True),
        sa.Column("source_window_end", sa.Date(), nullable=True),
        sa.Column("region_count", sa.Integer(), nullable=True),
        sa.Column("place_count", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.String(length=20),
            server_default=sa.text("'building'"),
            nullable=True,
        ),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("version_name"),
    )
    op.create_index(
        "idx_dataset_version_status", "dataset_version", ["status"], unique=False
    )

    # ------------------------------------------------------------------
    # 4. place_raw_kakao
    # ------------------------------------------------------------------
    op.create_table(
        "place_raw_kakao",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("region_id", sa.BigInteger(), nullable=False),
        sa.Column("source_place_id", sa.String(length=30), nullable=False),
        sa.Column("place_name", sa.String(length=200), nullable=False),
        sa.Column("category_name", sa.String(length=200), nullable=True),
        sa.Column("category_group_code", sa.String(length=10), nullable=True),
        sa.Column("category_group_name", sa.String(length=50), nullable=True),
        sa.Column("phone", sa.String(length=30), nullable=True),
        sa.Column("address_name", sa.String(length=300), nullable=True),
        sa.Column("road_address_name", sa.String(length=300), nullable=True),
        sa.Column("x", sa.Float(), nullable=False),
        sa.Column("y", sa.Float(), nullable=False),
        sa.Column("place_url", sa.String(length=500), nullable=True),
        sa.Column("distance", sa.String(length=20), nullable=True),
        sa.Column("raw_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("search_type", sa.String(length=20), nullable=False),
        sa.Column("search_query", sa.String(length=100), nullable=True),
        sa.Column(
            "collected_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=True,
        ),
        sa.Column("batch_id", sa.String(length=50), nullable=True),
        sa.ForeignKeyConstraint(["region_id"], ["region_master.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "source_place_id", "region_id", name="uq_place_raw_source_region"
        ),
    )
    op.create_index(
        "idx_place_raw_region", "place_raw_kakao", ["region_id"], unique=False
    )
    op.create_index(
        "idx_place_raw_source_id",
        "place_raw_kakao",
        ["source_place_id"],
        unique=False,
    )
    op.create_index(
        "idx_place_raw_batch", "place_raw_kakao", ["batch_id"], unique=False
    )

    # ------------------------------------------------------------------
    # 5. place_normalized
    # ------------------------------------------------------------------
    op.create_table(
        "place_normalized",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("region_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "source",
            sa.String(length=20),
            server_default=sa.text("'kakao'"),
            nullable=True,
        ),
        sa.Column("source_place_id", sa.String(length=30), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("primary_category", sa.String(length=30), nullable=False),
        sa.Column("sub_category", sa.String(length=100), nullable=True),
        sa.Column("lng", sa.Float(), nullable=False),
        sa.Column("lat", sa.Float(), nullable=False),
        sa.Column("address_name", sa.String(length=300), nullable=True),
        sa.Column("road_address_name", sa.String(length=300), nullable=True),
        sa.Column(
            "is_food",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=True,
        ),
        sa.Column(
            "is_cafe",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=True,
        ),
        sa.Column(
            "is_activity",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=True,
        ),
        sa.Column(
            "is_park",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=True,
        ),
        sa.Column(
            "is_culture",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=True,
        ),
        sa.Column(
            "is_nightlife",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=True,
        ),
        sa.Column(
            "is_lesson",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=True,
        ),
        sa.Column(
            "is_night_friendly",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=True,
        ),
        sa.Column(
            "is_group_friendly",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=True,
        ),
        sa.Column(
            "mapping_confidence",
            sa.Float(),
            server_default=sa.text("1.0"),
            nullable=True,
        ),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["region_id"], ["region_master.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "source", "source_place_id", name="uq_place_norm_source"
        ),
    )
    op.create_index(
        "idx_place_norm_region", "place_normalized", ["region_id"], unique=False
    )
    op.create_index(
        "idx_place_norm_category",
        "place_normalized",
        ["primary_category"],
        unique=False,
    )

    # ------------------------------------------------------------------
    # 6. real_activity_agg
    # ------------------------------------------------------------------
    op.create_table(
        "real_activity_agg",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("region_id", sa.BigInteger(), nullable=False),
        sa.Column("window_start", sa.Date(), nullable=False),
        sa.Column("window_end", sa.Date(), nullable=False),
        sa.Column(
            "real_spot_count",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=True,
        ),
        sa.Column(
            "real_join_count",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=True,
        ),
        sa.Column(
            "real_completion_count",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=True,
        ),
        sa.Column(
            "real_cancel_count",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=True,
        ),
        sa.Column(
            "real_noshow_count",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=True,
        ),
        sa.Column("completion_rate", sa.Float(), nullable=True),
        sa.Column("cancel_rate", sa.Float(), nullable=True),
        sa.Column("noshow_rate", sa.Float(), nullable=True),
        sa.Column(
            "real_food_spot_ratio",
            sa.Float(),
            server_default=sa.text("0"),
            nullable=True,
        ),
        sa.Column(
            "real_activity_spot_ratio",
            sa.Float(),
            server_default=sa.text("0"),
            nullable=True,
        ),
        sa.Column(
            "real_lesson_spot_ratio",
            sa.Float(),
            server_default=sa.text("0"),
            nullable=True,
        ),
        sa.Column(
            "real_night_spot_ratio",
            sa.Float(),
            server_default=sa.text("0"),
            nullable=True,
        ),
        sa.Column(
            "time_slot_distribution",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("real_avg_group_size", sa.Float(), nullable=True),
        sa.Column("real_hot_score", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["region_id"], ["region_master.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "region_id",
            "window_start",
            "window_end",
            name="uq_real_activity_region_window",
        ),
    )

    # ------------------------------------------------------------------
    # 7. region_feature
    # ------------------------------------------------------------------
    op.create_table(
        "region_feature",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("region_id", sa.BigInteger(), nullable=False),
        sa.Column("dataset_version", sa.String(length=50), nullable=False),
        sa.Column(
            "food_density", sa.Float(), server_default=sa.text("0"), nullable=True
        ),
        sa.Column(
            "cafe_density", sa.Float(), server_default=sa.text("0"), nullable=True
        ),
        sa.Column(
            "activity_density",
            sa.Float(),
            server_default=sa.text("0"),
            nullable=True,
        ),
        sa.Column(
            "nightlife_density",
            sa.Float(),
            server_default=sa.text("0"),
            nullable=True,
        ),
        sa.Column(
            "lesson_density",
            sa.Float(),
            server_default=sa.text("0"),
            nullable=True,
        ),
        sa.Column(
            "park_access_score",
            sa.Float(),
            server_default=sa.text("0"),
            nullable=True,
        ),
        sa.Column(
            "culture_score",
            sa.Float(),
            server_default=sa.text("0"),
            nullable=True,
        ),
        sa.Column(
            "night_liveliness_score",
            sa.Float(),
            server_default=sa.text("0"),
            nullable=True,
        ),
        sa.Column(
            "casual_meetup_score",
            sa.Float(),
            server_default=sa.text("0"),
            nullable=True,
        ),
        sa.Column(
            "lesson_spot_score",
            sa.Float(),
            server_default=sa.text("0"),
            nullable=True,
        ),
        sa.Column(
            "solo_activity_score",
            sa.Float(),
            server_default=sa.text("0"),
            nullable=True,
        ),
        sa.Column(
            "group_activity_score",
            sa.Float(),
            server_default=sa.text("0"),
            nullable=True,
        ),
        sa.Column("kakao_raw_score", sa.Float(), nullable=True),
        sa.Column("real_data_score", sa.Float(), nullable=True),
        sa.Column("blended_score", sa.Float(), nullable=True),
        sa.Column("alpha_used", sa.Float(), nullable=True),
        sa.Column("beta_used", sa.Float(), nullable=True),
        sa.Column(
            "raw_place_count",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=True,
        ),
        sa.Column(
            "normalized_place_count",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=True,
        ),
        sa.Column(
            "feature_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["region_id"], ["region_master.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "region_id",
            "dataset_version",
            name="uq_region_feature_region_version",
        ),
    )

    # ------------------------------------------------------------------
    # 8. persona_region_weight
    # ------------------------------------------------------------------
    op.create_table(
        "persona_region_weight",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("dataset_version", sa.String(length=50), nullable=False),
        sa.Column("persona_type", sa.String(length=50), nullable=False),
        sa.Column("region_id", sa.BigInteger(), nullable=False),
        sa.Column("affinity_score", sa.Float(), nullable=False),
        sa.Column("create_offer_score", sa.Float(), nullable=True),
        sa.Column("create_request_score", sa.Float(), nullable=True),
        sa.Column("join_score", sa.Float(), nullable=True),
        sa.Column(
            "explanation_json",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["region_id"], ["region_master.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "dataset_version",
            "persona_type",
            "region_id",
            name="uq_persona_region_weight",
        ),
    )

    # ------------------------------------------------------------------
    # 9. spot_seed_dataset
    # ------------------------------------------------------------------
    op.create_table(
        "spot_seed_dataset",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("dataset_version", sa.String(length=50), nullable=False),
        sa.Column("region_id", sa.BigInteger(), nullable=False),
        sa.Column("spot_type", sa.String(length=50), nullable=False),
        sa.Column("category", sa.String(length=30), nullable=False),
        sa.Column("expected_demand_score", sa.Float(), nullable=True),
        sa.Column("expected_supply_score", sa.Float(), nullable=True),
        sa.Column("recommended_capacity", sa.Integer(), nullable=True),
        sa.Column(
            "recommended_time_slots",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("price_band", sa.String(length=20), nullable=True),
        sa.Column("final_weight", sa.Float(), nullable=False),
        sa.Column(
            "payload_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["region_id"], ["region_master.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "dataset_version",
            "region_id",
            "spot_type",
            "category",
            name="uq_spot_seed_version_region_type_category",
        ),
    )


def downgrade() -> None:
    # Drop in the exact reverse of the upgrade order.
    op.drop_table("spot_seed_dataset")
    op.drop_table("persona_region_weight")
    op.drop_table("region_feature")
    op.drop_table("real_activity_agg")

    op.drop_index("idx_place_norm_category", table_name="place_normalized")
    op.drop_index("idx_place_norm_region", table_name="place_normalized")
    op.drop_table("place_normalized")

    op.drop_index("idx_place_raw_batch", table_name="place_raw_kakao")
    op.drop_index("idx_place_raw_source_id", table_name="place_raw_kakao")
    op.drop_index("idx_place_raw_region", table_name="place_raw_kakao")
    op.drop_table("place_raw_kakao")

    op.drop_index("idx_dataset_version_status", table_name="dataset_version")
    op.drop_table("dataset_version")

    op.drop_table("category_mapping_rule")

    op.drop_index("idx_region_last_collected", table_name="region_master")
    op.drop_index("idx_region_active", table_name="region_master")
    op.drop_index("idx_region_target_city", table_name="region_master")
    op.drop_table("region_master")
